#!/bin/bash
export INPUT_TARGET_ADDRESS=127.0.0.1
export INPUT_EXPORT_TO=html
export INPUT_WILL_EXIT_ON_FAIL=yes
export INPUT_MIN_PERFORMANCE=0.5
export INPUT_MIN_ACCESSIBILITY=0.5
export INPUT_MIN_BEST_PRACTICES=0.5
export INPUT_MIN_SEO=0.5
export INPUT_MIN_PWA=0.5
